spring:
  application:
    name: sensor-data-service
server:
  port: 8081
datasource:
  url: ${datasource.url:jdbc:mysql://localhost:3306/iot_db?allowPublicKeyRetrieval=true&useSSL=false}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${datasource.username}
  password: ${datasource.password}
  hikari:
    maximum-pool-size: 10
jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  properties:
    hibernate:
      format_sql: true