spring:
  application:
    name: user-service
server:
  port: 8082
datasource:
  url: jdbc:mysql://localhost:3306/iot_db?allowPublicKeyRetrieval=true&useSSL=false
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: harbaoui
  password: 12345678
  hikari:
    maximum-pool-size: 10
jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  properties:
    hibernate:
      format_sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: medamineharbaoui1@gmail.com
  password: kekr rtxr nnby rcwi
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
jwt:
  secret: MHJheDQ4cWxlNjVqYjVvYWF6cXRjbHRuNm5pMnd3d2k=